<?php
$a="10";
echo (int)($a);
echo "<br>";
echo gettype((int)($a));
echo "<br>";
echo "#################";
echo "<br>";
echo intval($a);
echo "<br>";
echo gettype(intval($a));
echo "<br>";
echo "#################";
echo "<br>";
$b=$a+0;
echo $b;
echo "<br>";
echo gettype($b);
echo "<br>";
echo "#################";
echo "<br>";